title: "MoCA Lab"
tagline: "Mobility Computation & Analytics Lab"
description: "MoCA (Mobility Computation & Analytics) is a research lab at the Technion focusing on mobility systems, infrastructure analytics, and computation methods."
url: "https://moca-technion.github.io"
baseurl: ""

theme: bulma-clean-theme
permalink: pretty
fixed_navbar: top
theme_color: "#002147"

footer_menu: footer_menu

plugins:
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

scholar:
  author_id: "lEg_t6kAAAAJ"
  hl: "en"
  sort: "pubdate"

collections:
  people:
    output: true
    permalink: /people/:name/
  news:
    output: true
    permalink: /news/:name/
    
defaults:
  - scope:
      path: "_people"
      type: "people"
    values:
      layout: "person"
  - scope:
      path: "_news"
      type: "news"
    values:
      layout: "news"

exclude:
  - scripts/
  - README.md


sass:
  style: compressed
